### ISSUE TITLE
Compile to wasm and host web demo

### ISSUE THREAD

**Issue by dgkf** [dgkf/R#28]
Explore compiling for web and possibly hosting a small browser demo.

Under-informed ideas, looking for input:

- Not sure how much overhead it's going to take to build a tiny page, but I might split this out into a separate repo if it feels like it's going to clutter things too much.
- Perhaps feature-gate wasm binding generation? Not sure if it makes more sense to build bindings into the core crate or to repackage just the repl with bindings as a separate project.

**Comment by dgkf** [comment]
I think I'm getting there, but running into a seemingly long-standing bug with `wasm_bindgen_cli`

```
wasm-pack build --target web --no-default-features --features wasm
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling r v0.1.1 (~/Projects/Programming/R)
    Finished release [optimized] target(s) in 6.63s
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-cli-support-0.2.87/src/descriptor.rs:218:15
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:162:5
   3: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   4: wasm_bindgen_cli_support::descriptor::Function::decode
   5: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   6: wasm_bindgen_cli_support::descriptors::execute
   7: wasm_bindgen_cli_support::Bindgen::generate_output
   8: wasm_bindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Running the wasm-bindgen CLI
Caused by: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101
  full command: "~/.cargo/bin/wasm-bindgen" "~/Projects/Programming/R/target/wasm32-unknown-unknown/release/r.wasm" "--out-dir" "~/Projects/Programming/R/pkg" "--typescript" "--target" "web"
```

Looking through the `wasm_bindgen` issues, it looks like people report this pretty frequently and the issue is often a mismatch in the `wasm_bindgen_cli` version and `wasm_bindgen` version, which seem to need to be kept in sync? From what I can tell both are on latest (`0.2.87`), so I'm not sure where things are going wrong.

**Comment by dgkf** [comment]
We have a wasm version deployed on pages now! :rocket:

**Comment by eitsupi** [comment]
Awesome!
